### ISSUE TITLE
能提供一下项目截图和演示吗？

### ISSUE THREAD

**Issue by Asphelzhn** [tusdasa/evaluation#2]
非常感谢

**Comment by tusdasa** [comment]
不好意思现在比较忙，截图是从论文里找的。已经更新到中[Wiki](https://github.com/tusdasa/evaluation/wiki)了，稍后会进一步更新。

**Comment by Asphelzhn** [comment]
非常感谢，方便提供一下论文吗，想学习一下

**Comment by Asphelzhn** [comment]
> [Error] invalid document for insert: keys cannot begin with "$": "$numberInt"
Mongodb语句执行有问题，是不是应该是
{"_id":NumberInt(1),"_class":"net.tusdasa.evaluation.entity.Right","firstKpiId":[NumberInt(5)],"secondKpiId":[NumberInt(28),NumberInt(29),NumberInt(30),NumberInt(31),NumberInt(32),NumberInt(33),NumberInt(34)],"thirdKpiId":[NumberInt(1),NumberInt(2),NumberInt(3),NumberInt(4),NumberInt(5),NumberInt(6),NumberInt(7),NumberInt(8),NumberInt(9),NumberInt(10),NumberInt(11),NumberInt(12),NumberInt(13),NumberInt(14),NumberInt(15),NumberInt(16),NumberInt(17),NumberInt(18),NumberInt(19),NumberInt(20)]}
{"_id":NumberInt(3),"_class":"net.tusdasa.evaluation.entity.Right","firstKpiId":[NumberInt(4)],"secondKpiId":[NumberInt(25),NumberInt(26),NumberInt(27),NumberInt(35),NumberInt(36),NumberInt(38)],"thirdKpiId":[NumberInt(21),NumberInt(22),NumberInt(23),NumberInt(24),NumberInt(25),NumberInt(26),NumberInt(27),NumberInt(28),NumberInt(29),NumberInt(30),NumberInt(31),NumberInt(33),NumberInt(34)]}

**Comment by tusdasa** [comment]
wiki已经更新，请查看[wiki](https://github.com/tusdasa/evaluation/wiki/Get-Started#%E9%85%8D%E7%BD%AE)

**Comment by Asphelzhn** [comment]
> wiki已经更新，请查看[wiki](https://github.com/tusdasa/evaluation/wiki/Get-Started#%E9%85%8D%E7%BD%AE)

感谢作者，方便提供一下论文参阅吗？568718851@qq.com，感激

**Comment by tusdasa** [comment]
论文：[基于Spring Cloud的教师教学评价系统的设计与实现.pdf](https://github.com/tusdasa/evaluation/files/5200347/Spring.Cloud.pdf)。水平有限，望请批评指正。
